export const LANDING = "/"
export const LOGIN = "/app/login"
export const SIGNUP = "/app/signup"
export const DASHBOARD = "/app/dashboard"
export const PRIVACY = "/privacy"
export const TERMS = "/terms"
